# Generated by Django 5.2.5 on 2025-08-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MotivoFalloSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='no code', max_length=20)),
                ('nombre', models.CharField(default='no name', max_length=100)),
                ('descripcion', models.TextField(default='no description')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_planilla', models.CharField(max_length=50, unique=True, verbose_name='Número de planilla')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=50, unique=True, verbose_name='Número de seguimiento')),
                ('direccion_destinatario', models.CharField(max_length=200, verbose_name='Dirección del destinatario')),
                ('telefono_destinatario', models.CharField(max_length=20, verbose_name='Teléfono del destinatario')),
                ('nombre_destinatario', models.CharField(max_length=100, verbose_name='Nombre del destinatario')),
                ('peso', models.FloatField(help_text='En gramos', verbose_name='Peso')),
                ('altura', models.FloatField(help_text='En centímetros', verbose_name='Altura')),
                ('estado', models.CharField(choices=[('en_deposito', 'En depósito'), ('en_distribucion', 'En distribución')], default='en_deposito', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(blank=True, choices=[('P', 'Pequeño (<1000g)'), ('M', 'Mediano (<3000g)'), ('G', 'Grande (≥3000g)')], max_length=1, verbose_name='Tipo de paquete')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='app_paquetes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'ordering': ['-estado', 'tracking'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(verbose_name='Posición')),
                ('motivo_fallo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_paquetes.motivofallosimple', verbose_name='Motivo de fallo')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_paquetes.paquete', verbose_name='Paquete')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_paquetes.planilla', verbose_name='Planilla')),
            ],
            options={
                'verbose_name': 'Ítem de Planilla',
                'verbose_name_plural': 'Ítems de Planilla',
                'ordering': ['posicion'],
            },
        ),
        migrations.AddIndex(
            model_name='paquete',
            index=models.Index(fields=['estado'], name='app_paquete_estado_2aa5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paquete',
            index=models.Index(fields=['tipo'], name='app_paquete_tipo_7228ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('planilla', 'paquete'), name='unique_planilla_paquete'),
        ),
    ]
