# Generated by Django 5.2.5 on 2025-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Mediano'), ('G', 'Grande')], max_length=1, verbose_name='Tipo de paquete'),
        ),
    ]
